apiVersion: v1
kind: ConfigMap
metadata:
  name: app-three-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>app3</title>
    </head>
    <body>
        <h1>Yo</h1>
    </body>
    </html>
