apiVersion: v1
kind: Pod
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  containers:
  - name: app-one-container
    image: nginx
    ports:
      - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#   selector:
#     app: app-one
