

BOX = "generic/alpine317"
BOX_VERSION = "4.3.12"

SERVER_NAME = "pcamarenS"
SERVER_IP = "192.168.56.110"

WORKER_NAME = "pcamarenSW"
WORKER_IP = "192.168.56.111"

CPU = 1
MEMORY = 1024

Vagrant.configure("2") do |config|

  config.vm.box = BOX
  config.vm.box_version = BOX_VERSION

  config.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPU
  end

  config.vm.define SERVER_NAME do |control|
    control.vm.hostname = SERVER_NAME
    control.vm.network "private_network", ip: SERVER_IP
    config.vm.provision "shell", path: "installation/ks3_install_server.sh"
  end

  config.vm.define WORKER_NAME do |control|
    control.vm.hostname = WORKER_NAME
    control.vm.network "private_network", ip: WORKER_IP
    config.vm.provision "shell", path: "installation/ks3_install_worker.sh"

  end

end
