

BOX = "generic/alpine317"
BOX_VERSION = "4.3.12"

SERVER_NAME = "pcamarenS"
SERVER_IP = "192.168.56.110"

WORKER_NAME = "pcamarenSW"
WORKER_IP = "192.168.56.111"

CPU = 1
MEMORY = 1024

Vagrant.configure("2") do |config|

  config.vm.box = BOX
  config.vm.box_version = BOX_VERSION
  config.vm.synced_folder ".", "/vagrant"

  # config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPU
  end

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    # control.vm.synced_folder "./installation/shared", "/home/vagrant/shared", type: VM_PROVIDER
    server.vm.provision "shell", path: "installation/ks3_install_server.sh",  env: {"SERVER_IP" => SERVER_IP}
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network "private_network", ip: WORKER_IP
    # control.vm.synced_folder "./installation/shared", "/home/vagrant/shared", type: VM_PROVIDER
    worker.vm.provision "shell", path: "installation/ks3_install_worker.sh",  env: {"SERVER_IP" => SERVER_IP, "WORKER_IP" => WORKER_IP}

  end

end
