apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Welcome to App One!</title></head>
    <body>
    <h1>Hello, World!</h1>
    </body>
    </html>
